# -*- coding: utf-8 -*-

#Created on  Jul 20 11:43:52 2016

#@author: Ankit Singh
Main:
    Input : 'C:\Users\310247467\Desktop\learn\qr\Input\'
    Output: 'C:\Users\310247467\Desktop\learn\qr\Results\'
FileType:
    - jpg
    - png
