# Camera calibration 

#640
camera_fx: 380.11939
camera_fy: 380.11939
camera_cx: 383.66979
camera_cy: 255.713731

#320
#camera_fx: 179.51961970424955
#camera_fy: 180.14811005619956
#camera_cx: 174.2833669046884
#camera_cy: 132.817497627893

# stereo baseline 0.06m
camera_bf: 60

# camera mode and video_num. mode: 0 for video 1 for topic. 
camera_mode: 1
camera_video_num: 0

# camera topic to subscribe
camera_topic: '/image_raw'
camera_topic_left: '/camera/left/image_raw'
camera_topic_right: '/camera/right/image_raw'

#window
window_hsv_low: 
  - 6
  - 47
  - 0
window_hsv_high:
  - 56
  - 255
  - 255

