# Camera calibration 
camera_fx: 443
camera_fy: 443

# stereo baseline times fx    base=0.06
camera_bf: 60

# camera topic to subscribe
camera_topic: '/image_raw'
camera_topic_left: '/left/image_rect_color'
camera_topic_right: '/right/image_rect_color'
